"""empty message

Revision ID: 1dba17f3700f
Revises: 
Create Date: 2026-02-22 02:41:14.813037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dba17f3700f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Matches_UUID'), 'Matches', ['UUID'], unique=True)
    op.create_index(op.f('ix_Players_Name'), 'Players', ['Name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Players_Name'), table_name='Players')
    op.drop_index(op.f('ix_Matches_UUID'), table_name='Matches')
    # ### end Alembic commands ###
